s1 = """CMODE_CHARMAP_CLI_006
CMODE_CHARMAP_CLI_007
CMODE_CHARMAP_CLI_008
CMODE_CHARMAP_CLI_010
CMODE_CHARMAP_CLI_011
CMODE_CHARMAP_CLI_013
CMODE_CHARMAP_CLI_014
CMODE_CHARMAP_CLI_015
CMODE_CHARMAP_CLI_016
CMODE_CHARMAP_CLI_017
CMODE_CHARMAP_CLI_018
CMODE_CHARMAP_CLI_021
CHARMAP_FUNCTIONALITY_001
CHARMAP_FUNCTIONALITY_002
CHARMAP_FUNCTIONALITY_003
CHARMAP_FUNCTIONALITY_004
CHARMAP_FUNCTIONALITY_006
CHARMAP_FUNCTIONALITY_008
CHARMAP_FUNCTIONALITY_010
CHARMAP_FUNCTIONALITY_012
CHARMAP_FUNCTIONALITY_013
CHARMAP_FUNCTIONALITY_014
CHARMAP_FUNCTIONALITY_015
CHARMAP_FUNCTIONALITY_016
CHARMAP_FUNCTIONALITY_017
CHARMAP_FUNCTIONALITY_021
CHARMAP_FUNCTIONALITY_022
CHARMAP_FUNCTIONALITY_024 
CHARMAP_FUNCTIONALITY_027
CHARMAP_FUNCTIONALITY_029
CHARMAP_FUNCTIONALITY_034
CHARMAP_FUNCTIONALITY_035
CHARMAP_FUNCTIONALITY_036
CHARMAP_FUNCTIONALITY_037
CHARMAP_FUNCTIONALITY_038
CHARMAP_FUNCTIONALITY_039
CHARMAP_FUNCTIONALITY_041
CHARMAP_FUNCTIONALITY_042
CHARMAP_FUNCTIONALITY_045
CHARMAP_FUNCTIONALITY_047
CHARMAP_FUNCTIONALITY_051
CHARMAP_FUNCTIONALITY_052
CHARMAP_FUNCTIONALITY_053
CHARMAP_FUNCTIONALITY_054
CHARMAP_FUNCTIONALITY_055
CMODE_CHARMAP_CLI_001
"""
s2 = """SN_FPOLICY_ZAPI_EVTCREATE_001
SN_FPOLICY_ZAPI_EVTCREATE_003
SN_FPOLICY_ZAPI_EVTCREATE_002
SN_FPOLICY_ZAPI_EVTCREATE_004
SN_FPOLICY_ZAPI_EVTCREATE_005
SN_FPOLICY_ZAPI_EVTDELETE_001
SN_FPOLICY_ZAPI_EVTDELETE_002
SN_FPOLICY_ZAPI_EVTMODIFY_001
SN_FPOLICY_ZAPI_EVTMODIFY_002
SN_FPOLICY_ZAPI_EVTMODIFY_003
SN_FPOLICY_ZAPI_EVTMODIFY_004
SN_FPOLICY_ZAPI_EVTMODIFY_005
SN_FPOLICY_ZAPI_EECREATE_001
SN_FPOLICY_ZAPI_EECREATE_016
SN_FPOLICY_ZAPI_EECREATE_002
SN_FPOLICY_ZAPI_EECREATE_005
SN_FPOLICY_ZAPI_EECREATE_003
SN_FPOLICY_ZAPI_EEDELETE_005
SN_FPOLICY_ZAPI_EEDELETE_001
SN_FPOLICY_ZAPI_EEMODIFY_005
SN_FPOLICY_ZAPI_EEMODIFY_004
SN_FPOLICY_ZAPI_EEMODIFY_003
SN_FPOLICY_ZAPI_FPCREATE_001
SN_FPOLICY_ZAPI_FPCREATE_007
SN_FPOLICY_ZAPI_FPCREATE_005
SN_FPOLICY_ZAPI_FPCREATE_006
SN_FPOLICY_ZAPI_FPDELETE_001
SN_FPOLICY_ZAPI_FPDELETE_002
SN_FPOLICY_ZAPI_FPMODIFY_006
SN_FPOLICY_ZAPI_FPMODIFY_003
SN_FPOLICY_ZAPI_FPMODIFY_004
SN_FPOLICY_ZAPI_FPMODIFY_005
SN_FPOLICY_ZAPI_SCOPECREATE_016
SN_FPOLICY_ZAPI_SCOPECREATE_007
SN_FPOLICY_ZAPI_SCOPECREATE_009
SN_FPOLICY_ZAPI_SCOPECREATE_011
SN_FPOLICY_ZAPI_SCOPEDELETE_002
SN_FPOLICY_ZAPI_SCOPEDELETE_001
SN_FPOLICY_ZAPI_SCOPEMODIFY_001
SN_FPOLICY_ZAPI_SCOPEMODIFY_003
SN_FPOLICY_ZAPI_SCOPEMODIFY_007
SN_FPOLICY_ZAPI_SCOPEMODIFY_008
SN_FPOLICY_ZAPI_FPDISABLE_001
SN_FPOLICY_ZAPI_FPDISABLE_005
SN_FPOLICY_ZAPI_FPENABLE_001
SN_FPOLICY_ZAPI_FPENABLE_002
SN_FPOLICY_ZAPI_FPENABLE_006
SN_FPOLICY_ZAPI_FPCREATE_004
SN_FPOLICY_ZAPI_FPCREATE_011
SN_FPOLICY_ZAPI_FPCREATE_012
SN_FPOLICY_ZAPI_FPDELETE_005
SN_FPOLICY_ZAPI_FPMODIFY_001
SN_FPOLICY_ZAPI_FPMODIFY_002
SN_FPOLICY_ZAPI_FPMODIFY_009
SN_FPOLICY_ZAPI_FPENABLE_003
SN_FPOLICY_ZAPI_EECREATE_006
SN_FPOLICY_ZAPI_EECREATE_007
SN_FPOLICY_ZAPI_EECREATE_008
SN_FPOLICY_ZAPI_EECREATE_009
SN_FPOLICY_ZAPI_EECREATE_010
SN_FPOLICY_ZAPI_EECREATE_011
SN_FPOLICY_ZAPI_EECREATE_012
SN_FPOLICY_ZAPI_EECREATE_013
SN_FPOLICY_ZAPI_EEMODIFY_002
SN_FPOLICY_ZAPI_EEMODIFY_006
SN_FPOLICY_ZAPI_EEMODIFY_001
SN_FPOLICY_ZAPI_EEMODIFY_007
SN_FPOLICY_ZAPI_EEMODIFY_008
SN_FPOLICY_ZAPI_EEMODIFY_009
SN_FPOLICY_ZAPI_EEMODIFY_010
SN_FPOLICY_ZAPI_EEMODIFY_011
SN_FPOLICY_ZAPI_EEMODIFY_012
SN_FPOLICY_ZAPI_EEMODIFY_017
SN_FPOLICY_ZAPI_EEMODIFY_014
SN_FPOLICY_ZAPI_SCOPECREATE_008
SN_FPOLICY_ZAPI_SCOPECREATE_010
SN_FPOLICY_ZAPI_SCOPECREATE_012
SN_FPOLICY_ZAPI_SCOPECREATE_013
SN_FPOLICY_ZAPI_SCOPECREATE_014
SN_FPOLICY_ZAPI_SCOPEMODIFY_002
SN_FPOLICY_ZAPI_SCOPEMODIFY_004
SN_FPOLICY_ZAPI_SCOPEMODIFY_005
SN_FPOLICY_ZAPI_SCOPEMODIFY_006
SN_FPOLICY_ZAPI_FPCREATE_009
SN_FPOLICY_ZAPI_FPSHOW_005
SN_FPOLICY_ZAPI_FPDELETE_004
SN_FPOLICY_ZAPI_FPMODIFY_008
SN_FPOLICY_ZAPI_FPENABLE_005
SN_FPOLICY_ZAPI_FPDISABLE_004
SN_FPOLICY_ZAPI_EECREATE_018
SN_FPOLICY_ZAPI_EEDELETE_004
SN_FPOLICY_ZAPI_EEMODIFY_016
SN_FPOLICY_ZAPI_EVTCREATE_009
SN_FPOLICY_ZAPI_SCOPECREATE_018
SN_FPOLICY_ZAPI_SCOPEMODIFY_011
SN_FPOLICY_ZAPI_SCOPEDELETE_005
SN_FPOLICY_ZAPI_FPSTATUS_001
SN_FPOLICY_ZAPI_SRVCONNECT_001
SN_FPOLICY_ZAPI_SRVCONNECT_003
SN_FPOLICY_ZAPI_SRVCONNECT_006
SN_FPOLICY_ZAPI_SRVCONNECT_007
SN_FPOLICY_ZAPI_SRVCONNECT_008
SN_FPOLICY_ZAPI_SRVDISCONNECT_001
SN_FPOLICY_ZAPI_SRVDISCONNECT_006
SN_FPOLICY_ZAPI_SRVDISCONNECT_007
SN_FPOLICY_ZAPI_SRVDISCONNECT_008
SN_FPOLICY_ZAPI_SRVSTATUS_001
SN_FPOLICY_ZAPI_EVTCREATE_001"""

s = s2
print("Test Case Count: %s"%len(s.split("\n")))
stc = s.split("\n")
print(','.join(stc))
s3 = """PASS: Test case SN_FPOLICY_ZAPI_EVTCREATE_001
PASS: Test case SN_FPOLICY_ZAPI_EVTCREATE_003
PASS: Test case SN_FPOLICY_ZAPI_EVTCREATE_002
PASS: Test case SN_FPOLICY_ZAPI_EVTCREATE_004
PASS: Test case SN_FPOLICY_ZAPI_EVTCREATE_005
PASS: Test case SN_FPOLICY_CLI_EVENT_CREATE_017
PASS: Test case SN_FPOLICY_CLI_EVENT_CREATE_018
PASS: Test case SN_FPOLICY_ZAPI_EVTDELETE_001
PASS: Test case SN_FPOLICY_ZAPI_EVTDELETE_002
PASS: Test case SN_FPOLICY_CLI_EVENT_DELETE_004
PASS: Test case SN_FPOLICY_CLI_EVENT_DELETE_005
PASS: Test case SN_FPOLICY_ZAPI_EVTMODIFY_001
PASS: Test case SN_FPOLICY_ZAPI_EVTMODIFY_002
PASS: Test case SN_FPOLICY_ZAPI_EVTMODIFY_003
PASS: Test case SN_FPOLICY_ZAPI_EVTMODIFY_004
PASS: Test case SN_FPOLICY_ZAPI_EVTMODIFY_005
PASS: Test case SN_FPOLICY_ZAPI_EECREATE_001
PASS: Test case SN_FPOLICY_CLI_ENGINE_CREATE_002
PASS: Test case SN_FPOLICY_CLI_ENGINE_CREATE_003
PASS: Test case SN_FPOLICY_ZAPI_EECREATE_016
PASS: Test case SN_FPOLICY_CLI_ENGINE_CREATE_005
PASS: Test case SN_FPOLICY_CLI_ENGINE_CREATE_006
PASS: Test case SN_FPOLICY_ZAPI_EECREATE_002
PASS: Test case SN_FPOLICY_ZAPI_EECREATE_005
PASS: Test case SN_FPOLICY_ZAPI_EECREATE_003
PASS: Test case SN_FPOLICY_CLI_ENGINE_CREATE_010
PASS: Test case SN_FPOLICY_ZAPI_EEDELETE_005
PASS: Test case SN_FPOLICY_ZAPI_EEDELETE_001
PASS: Test case SN_FPOLICY_CLI_ENGINE_DELETE_003
PASS: Test case SN_FPOLICY_CLI_ENGINE_MODIFY_001
PASS: Test case SN_FPOLICY_CLI_ENGINE_MODIFY_002
PASS: Test case SN_FPOLICY_CLI_ENGINE_MODIFY_003
PASS: Test case SN_FPOLICY_ZAPI_EEMODIFY_005
PASS: Test case SN_FPOLICY_ZAPI_EEMODIFY_004
PASS: Test case SN_FPOLICY_ZAPI_EEMODIFY_003
PASS: Test case SN_FPOLICY_CLI_ENGINE_MODIFY_007
PASS: Test case SN_FPOLICY_CLI_POLICY_CREATE_001
PASS: Test case SN_FPOLICY_ZAPI_FPCREATE_001
PASS: Test case SN_FPOLICY_CLI_POLICY_CREATE_004
PASS: Test case SN_FPOLICY_CLI_POLICY_CREATE_005
PASS: Test case SN_FPOLICY_ZAPI_FPCREATE_007
PASS: Test case SN_FPOLICY_CLI_POLICY_CREATE_007
PASS: Test case SN_FPOLICY_CLI_POLICY_CREATE_008
PASS: Test case SN_FPOLICY_ZAPI_FPCREATE_005
PASS: Test case SN_FPOLICY_ZAPI_FPCREATE_006
PASS: Test case SN_FPOLICY_CLI_POLICY_CREATE_012
PASS: Test case SN_FPOLICY_ZAPI_FPDELETE_001
PASS: Test case SN_FPOLICY_CLI_POLICY_DELETE_002
PASS: Test case SN_FPOLICY_ZAPI_FPDELETE_002_001
PASS: Test case SN_FPOLICY_ZAPI_FPDELETE_002
PASS: Test case SN_FPOLICY_ZAPI_FPMODIFY_006
PASS: Test case SN_FPOLICY_ZAPI_FPMODIFY_003
PASS: Test case SN_FPOLICY_ZAPI_FPMODIFY_004
PASS: Test case SN_FPOLICY_ZAPI_FPMODIFY_005
PASS: Test case SN_FPOLICY_CLI_POLICY_MODIFY_005
PASS: Test case SN_FPOLICY_CLI_POLICY_MODIFY_006
PASS: Test case SN_FPOLICY_CLI_POLICY_MODIFY_007
PASS: Test case SN_FPOLICY_CLI_POLICY_MODIFY_008
PASS: Test case SN_FPOLICY_ZAPI_SCOPECREATE_016
PASS: Test case SN_FPOLICY_ZAPI_SCOPECREATE_007
PASS: Test case SN_FPOLICY_ZAPI_SCOPECREATE_009
PASS: Test case SN_FPOLICY_ZAPI_SCOPECREATE_011
PASS: Test case SN_FPOLICY_ZAPI_SCOPEDELETE_002
PASS: Test case SN_FPOLICY_CLI_SCOPE_DELETE_002
PASS: Test case SN_FPOLICY_ZAPI_SCOPEDELETE_001
PASS: Test case SN_FPOLICY_ZAPI_SCOPEMODIFY_001
PASS: Test case SN_FPOLICY_ZAPI_SCOPEMODIFY_003
PASS: Test case SN_FPOLICY_ZAPI_SCOPEMODIFY_007
PASS: Test case SN_FPOLICY_ZAPI_SCOPEMODIFY_008
PASS: Test case SN_FPOLICY_ZAPI_FPDISABLE_001
PASS: Test case SN_FPOLICY_CLI_POLICY_DISABLE_002
PASS: Test case SN_FPOLICY_ZAPI_FPDISABLE_005
PASS: Test case SN_FPOLICY_ZAPI_FPENABLE_001
PASS: Test case SN_FPOLICY_ZAPI_FPENABLE_002
PASS: Test case SN_FPOLICY_CLI_POLICY_ENABLE_003
PASS: Test case SN_FPOLICY_ZAPI_FPENABLE_006
PASS: Test case SN_FPOLICY_ZAPI_FPCREATE_004
PASS: Test case SN_FPOLICY_ZAPI_FPCREATE_011
PASS: Test case SN_FPOLICY_ZAPI_FPCREATE_012
PASS: Test case SN_FPOLICY_ZAPI_FPDELETE_005
PASS: Test case SN_FPOLICY_ZAPI_FPMODIFY_001
PASS: Test case SN_FPOLICY_ZAPI_FPMODIFY_002
PASS: Test case SN_FPOLICY_ZAPI_FPMODIFY_009
PASS: Test case SN_FPOLICY_ZAPI_FPENABLE_003
PASS: Test case SN_FPOLICY_ZAPI_EECREATE_006
PASS: Test case SN_FPOLICY_ZAPI_EECREATE_007
PASS: Test case SN_FPOLICY_ZAPI_EECREATE_008
PASS: Test case SN_FPOLICY_ZAPI_EECREATE_009
PASS: Test case SN_FPOLICY_ZAPI_EECREATE_010
PASS: Test case SN_FPOLICY_ZAPI_EECREATE_011
PASS: Test case SN_FPOLICY_ZAPI_EECREATE_012
PASS: Test case SN_FPOLICY_ZAPI_EECREATE_013
PASS: Test case SN_FPOLICY_ZAPI_EEMODIFY_002
PASS: Test case SN_FPOLICY_ZAPI_EEMODIFY_006
PASS: Test case SN_FPOLICY_ZAPI_EEMODIFY_001
PASS: Test case SN_FPOLICY_ZAPI_EEMODIFY_007
PASS: Test case SN_FPOLICY_ZAPI_EEMODIFY_008
PASS: Test case SN_FPOLICY_ZAPI_EEMODIFY_009
PASS: Test case SN_FPOLICY_ZAPI_EEMODIFY_010
PASS: Test case SN_FPOLICY_ZAPI_EEMODIFY_011
PASS: Test case SN_FPOLICY_ZAPI_EEMODIFY_012
PASS: Test case SN_FPOLICY_ZAPI_EEMODIFY_017
PASS: Test case SN_FPOLICY_ZAPI_EEMODIFY_014
PASS: Test case SN_FPOLICY_ZAPI_SCOPECREATE_008
PASS: Test case SN_FPOLICY_ZAPI_SCOPECREATE_010
PASS: Test case SN_FPOLICY_ZAPI_SCOPECREATE_012
PASS: Test case SN_FPOLICY_ZAPI_SCOPECREATE_013
PASS: Test case SN_FPOLICY_ZAPI_SCOPECREATE_014
PASS: Test case SN_FPOLICY_ZAPI_SCOPEMODIFY_002
PASS: Test case SN_FPOLICY_ZAPI_SCOPEMODIFY_004
PASS: Test case SN_FPOLICY_ZAPI_SCOPEMODIFY_005
PASS: Test case SN_FPOLICY_ZAPI_SCOPEMODIFY_006
PASS: Test case SN_FPOLICY_ZAPI_FPCREATE_009
PASS: Test case SN_FPOLICY_ZAPI_FPSHOW_005
PASS: Test case SN_FPOLICY_ZAPI_FPDELETE_004
PASS: Test case SN_FPOLICY_ZAPI_FPMODIFY_008
PASS: Test case SN_FPOLICY_ZAPI_FPENABLE_005
PASS: Test case SN_FPOLICY_ZAPI_FPDISABLE_004
PASS: Test case SN_FPOLICY_ZAPI_EECREATE_018
PASS: Test case SN_FPOLICY_ZAPI_EEDELETE_004
PASS: Test case SN_FPOLICY_ZAPI_EEMODIFY_016
PASS: Test case SN_FPOLICY_ZAPI_EVTCREATE_009
PASS: Test case SN_FPOLICY_ZAPI_SCOPECREATE_018
PASS: Test case SN_FPOLICY_ZAPI_SCOPEMODIFY_011
PASS: Test case SN_FPOLICY_ZAPI_SCOPEDELETE_005
PASS: Test case SN_FPOLICY_ZAPI_FPSTATUS_001
PASS: Test case SN_FPOLICY_ZAPI_SRVCONNECT_001
PASS: Test case SN_FPOLICY_ZAPI_SRVCONNECT_003
PASS: Test case SN_FPOLICY_ZAPI_SRVCONNECT_006
PASS: Test case SN_FPOLICY_ZAPI_SRVCONNECT_007
PASS: Test case SN_FPOLICY_ZAPI_SRVCONNECT_008
PASS: Test case SN_FPOLICY_ZAPI_SRVDISCONNECT_001
PASS: Test case SN_FPOLICY_ZAPI_SRVDISCONNECT_006
PASS: Test case SN_FPOLICY_ZAPI_SRVDISCONNECT_007
PASS: Test case SN_FPOLICY_ZAPI_SRVDISCONNECT_008
PASS: Test case SN_FPOLICY_ZAPI_SRVSTATUS_001"""

s4="""CIFS_10M_01_AL_01
CIFS_10M_24_AL_24
CIFS_10M_25_AL_25
CIFS_10M_26_AL_26
CIFS_10M_03_AL_03
CIFS_10M_04_AL_04
CIFS_10M_05_AL_05
CIFS_10M_06_AL_06
CIFS_10M_02_AL_02
CIFS_10M_48_AL_48
CIFS_10M_19_AL_19
CIFS_10M_53_AL_53
CIFS_10M_45_AL_45
CIFS_10M_12_AL_12
CIFS_10M_16_AL_16
CIFS_10M_41_AL_41
CIFS_10M_73_AL_73
CIFS_10M_74_AL_74
CIFS_10M_75_AL_75
CIFS_10M_76_AL_76
CIFS_10M_77_AL_77
CIFS_10M_11_AL_11
CIFS_10M_50_AL_50
CIFS_10M_38_AL_38
CIFS_10M_46_AL_46
CIFS_10M_39_AL_39
CIFS_10M_07_AL_07
CIFS_10M_08_AL_08
CIFS_10M_09_AL_09
CIFS_10M_78_AL_78
CIFS_10M_79_AL_79"""
ts4 = s4.split("\n")
s5 = ['CIFS_10M_01_AL_01', 'CIFS_10M_03_AL_03', 'CIFS_10M_04_AL_04', 'CIFS_10M_05_AL_05', 'CIFS_10M_06_AL_06', 'CIFS_10M_23_AL_23', 'CIFS_10M_24_AL_24', 'CIFS_10M_25_AL_25', 'CIFS_10M_26_AL_26', 'CIFS_10M_02_AL_02', 'CIFS_10M_48_AL_48', 'CIFS_10M_18_AL_18', 'CIFS_10M_19_AL_19', 'CIFS_10M_15_AL_15', 'CIFS_10M_53_AL_53', 'CIFS_10M_45_AL_45', 'CIFS_10M_12_AL_12', 'CIFS_10M_16_AL_16', 'CIFS_10M_41_AL_41', 'CIFS_10M_73_AL_73', 'CIFS_10M_74_AL_74', 'CIFS_10M_75_AL_75', 'CIFS_10M_76_AL_76', 'CIFS_10M_77_AL_77', 'CIFS_10M_11_AL_11', 'CIFS_10M_50_AL_50', 'CIFS_10M_38_AL_38', 'CIFS_10M_46_AL_46', 'CIFS_10M_39_AL_39', 'CIFS_10M_07_AL_07', 'CIFS_10M_08_AL_08', 'CIFS_10M_09_AL_09', 'CIFS_10M_78_AL_78', 'CIFS_10M_79_AL_79', 'CIFS_10M_80_AL_80', 'CIFS_10M_81_AL_81']
print(len(s5))

s = s3
print("Test Case Count: %s"%len(s.split("\n")))
s3tc = [i.split('case ')[1] for i in s.split("\n")]
print(','.join([i.split('case ')[1] for i in s.split("\n")]))


def differnce_in_list(l1, l2):
    excludedtc = []
    print("Following TC from L1 list not present in L2")
    for tc in l1:
        if tc not in l2:
            print(tc)
            excludedtc.append(tc)
    print(len(excludedtc))
    return excludedtc
differnce_in_list(ts4,s5)
t = differnce_in_list(s5,ts4)
print(t)
print("Excluded : -----")
t = differnce_in_list(s3tc, stc)
print(t)
# exc = "SN_FPOLICY_CLI_EVENT_CREATE_008,SN_FPOLICY_CLI_EVENT_DELETE_003,SN_FPOLICY_CLI_ENGINE_DELETE_004,SN_FPOLICY_CLI_POLICY_CREATE_009,SN_FPOLICY_CLI_POLICY_DELETE_005,SN_FPOLICY_CLI_SCOPE_DELETE_003,SN_FPOLICY_CLI_SCOPE_MODIFY_005,SN_FPOLICY_CLI_POLICY_DISABLE_004,SN_FPOLICY_CLI_POLICY_ENABLE_005,SN_FPOLICY_CLI_POLICY_ENABLE_006,SN_FPOLICY_CLI_POLICY_ENABLE_007"
# print(len(exc.split(',')))
# differnce_in_list(t, exc.split(','))
# differnce_in_list(exc.split(','), t)